# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_nucleardata', [dirname(__file__)])
        except ImportError:
            import _nucleardata
            return _nucleardata
        if fp is not None:
            try:
                _mod = imp.load_module('_nucleardata', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _nucleardata = swig_import_helper()
    del swig_import_helper
else:
    import _nucleardata
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class NUCLEAR_DATA(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, NUCLEAR_DATA, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, NUCLEAR_DATA, name)
    __repr__ = _swig_repr
    __swig_setmethods__["SM2_NO_XE"] = _nucleardata.NUCLEAR_DATA_SM2_NO_XE_set
    __swig_getmethods__["SM2_NO_XE"] = _nucleardata.NUCLEAR_DATA_SM2_NO_XE_get
    if _newclass:SM2_NO_XE = _swig_property(_nucleardata.NUCLEAR_DATA_SM2_NO_XE_get, _nucleardata.NUCLEAR_DATA_SM2_NO_XE_set)
    __swig_setmethods__["M2_NO_XE"] = _nucleardata.NUCLEAR_DATA_M2_NO_XE_set
    __swig_getmethods__["M2_NO_XE"] = _nucleardata.NUCLEAR_DATA_M2_NO_XE_get
    if _newclass:M2_NO_XE = _swig_property(_nucleardata.NUCLEAR_DATA_M2_NO_XE_get, _nucleardata.NUCLEAR_DATA_M2_NO_XE_set)
    __swig_setmethods__["M2_XE"] = _nucleardata.NUCLEAR_DATA_M2_XE_set
    __swig_getmethods__["M2_XE"] = _nucleardata.NUCLEAR_DATA_M2_XE_get
    if _newclass:M2_XE = _swig_property(_nucleardata.NUCLEAR_DATA_M2_XE_get, _nucleardata.NUCLEAR_DATA_M2_XE_set)
    __swig_setmethods__["NUFISS1"] = _nucleardata.NUCLEAR_DATA_NUFISS1_set
    __swig_getmethods__["NUFISS1"] = _nucleardata.NUCLEAR_DATA_NUFISS1_get
    if _newclass:NUFISS1 = _swig_property(_nucleardata.NUCLEAR_DATA_NUFISS1_get, _nucleardata.NUCLEAR_DATA_NUFISS1_set)
    __swig_setmethods__["K2"] = _nucleardata.NUCLEAR_DATA_K2_set
    __swig_getmethods__["K2"] = _nucleardata.NUCLEAR_DATA_K2_get
    if _newclass:K2 = _swig_property(_nucleardata.NUCLEAR_DATA_K2_get, _nucleardata.NUCLEAR_DATA_K2_set)
    __swig_setmethods__["K1"] = _nucleardata.NUCLEAR_DATA_K1_set
    __swig_getmethods__["K1"] = _nucleardata.NUCLEAR_DATA_K1_get
    if _newclass:K1 = _swig_property(_nucleardata.NUCLEAR_DATA_K1_get, _nucleardata.NUCLEAR_DATA_K1_set)
    __swig_setmethods__["NUFISS2"] = _nucleardata.NUCLEAR_DATA_NUFISS2_set
    __swig_getmethods__["NUFISS2"] = _nucleardata.NUCLEAR_DATA_NUFISS2_get
    if _newclass:NUFISS2 = _swig_property(_nucleardata.NUCLEAR_DATA_NUFISS2_get, _nucleardata.NUCLEAR_DATA_NUFISS2_set)
    __swig_setmethods__["BOR1_NO_XE"] = _nucleardata.NUCLEAR_DATA_BOR1_NO_XE_set
    __swig_getmethods__["BOR1_NO_XE"] = _nucleardata.NUCLEAR_DATA_BOR1_NO_XE_get
    if _newclass:BOR1_NO_XE = _swig_property(_nucleardata.NUCLEAR_DATA_BOR1_NO_XE_get, _nucleardata.NUCLEAR_DATA_BOR1_NO_XE_set)
    __swig_setmethods__["BOR2_XE"] = _nucleardata.NUCLEAR_DATA_BOR2_XE_set
    __swig_getmethods__["BOR2_XE"] = _nucleardata.NUCLEAR_DATA_BOR2_XE_get
    if _newclass:BOR2_XE = _swig_property(_nucleardata.NUCLEAR_DATA_BOR2_XE_get, _nucleardata.NUCLEAR_DATA_BOR2_XE_set)
    __swig_setmethods__["REMOV1"] = _nucleardata.NUCLEAR_DATA_REMOV1_set
    __swig_getmethods__["REMOV1"] = _nucleardata.NUCLEAR_DATA_REMOV1_get
    if _newclass:REMOV1 = _swig_property(_nucleardata.NUCLEAR_DATA_REMOV1_get, _nucleardata.NUCLEAR_DATA_REMOV1_set)
    __swig_setmethods__["DIFF2"] = _nucleardata.NUCLEAR_DATA_DIFF2_set
    __swig_getmethods__["DIFF2"] = _nucleardata.NUCLEAR_DATA_DIFF2_get
    if _newclass:DIFF2 = _swig_property(_nucleardata.NUCLEAR_DATA_DIFF2_get, _nucleardata.NUCLEAR_DATA_DIFF2_set)
    __swig_setmethods__["DIFF1"] = _nucleardata.NUCLEAR_DATA_DIFF1_set
    __swig_getmethods__["DIFF1"] = _nucleardata.NUCLEAR_DATA_DIFF1_get
    if _newclass:DIFF1 = _swig_property(_nucleardata.NUCLEAR_DATA_DIFF1_get, _nucleardata.NUCLEAR_DATA_DIFF1_set)
    __swig_setmethods__["BOR1_XE"] = _nucleardata.NUCLEAR_DATA_BOR1_XE_set
    __swig_getmethods__["BOR1_XE"] = _nucleardata.NUCLEAR_DATA_BOR1_XE_get
    if _newclass:BOR1_XE = _swig_property(_nucleardata.NUCLEAR_DATA_BOR1_XE_get, _nucleardata.NUCLEAR_DATA_BOR1_XE_set)
    __swig_setmethods__["XE_YIELD"] = _nucleardata.NUCLEAR_DATA_XE_YIELD_set
    __swig_getmethods__["XE_YIELD"] = _nucleardata.NUCLEAR_DATA_XE_YIELD_get
    if _newclass:XE_YIELD = _swig_property(_nucleardata.NUCLEAR_DATA_XE_YIELD_get, _nucleardata.NUCLEAR_DATA_XE_YIELD_set)
    __swig_setmethods__["NU"] = _nucleardata.NUCLEAR_DATA_NU_set
    __swig_getmethods__["NU"] = _nucleardata.NUCLEAR_DATA_NU_get
    if _newclass:NU = _swig_property(_nucleardata.NUCLEAR_DATA_NU_get, _nucleardata.NUCLEAR_DATA_NU_set)
    __swig_setmethods__["BOR2_NO_XE"] = _nucleardata.NUCLEAR_DATA_BOR2_NO_XE_set
    __swig_getmethods__["BOR2_NO_XE"] = _nucleardata.NUCLEAR_DATA_BOR2_NO_XE_get
    if _newclass:BOR2_NO_XE = _swig_property(_nucleardata.NUCLEAR_DATA_BOR2_NO_XE_get, _nucleardata.NUCLEAR_DATA_BOR2_NO_XE_set)
    __swig_setmethods__["KAPPA"] = _nucleardata.NUCLEAR_DATA_KAPPA_set
    __swig_getmethods__["KAPPA"] = _nucleardata.NUCLEAR_DATA_KAPPA_get
    if _newclass:KAPPA = _swig_property(_nucleardata.NUCLEAR_DATA_KAPPA_get, _nucleardata.NUCLEAR_DATA_KAPPA_set)
    __swig_setmethods__["ABS1"] = _nucleardata.NUCLEAR_DATA_ABS1_set
    __swig_getmethods__["ABS1"] = _nucleardata.NUCLEAR_DATA_ABS1_get
    if _newclass:ABS1 = _swig_property(_nucleardata.NUCLEAR_DATA_ABS1_get, _nucleardata.NUCLEAR_DATA_ABS1_set)
    __swig_setmethods__["ABS2"] = _nucleardata.NUCLEAR_DATA_ABS2_set
    __swig_getmethods__["ABS2"] = _nucleardata.NUCLEAR_DATA_ABS2_get
    if _newclass:ABS2 = _swig_property(_nucleardata.NUCLEAR_DATA_ABS2_get, _nucleardata.NUCLEAR_DATA_ABS2_set)
    __swig_setmethods__["XE2_MAC"] = _nucleardata.NUCLEAR_DATA_XE2_MAC_set
    __swig_getmethods__["XE2_MAC"] = _nucleardata.NUCLEAR_DATA_XE2_MAC_get
    if _newclass:XE2_MAC = _swig_property(_nucleardata.NUCLEAR_DATA_XE2_MAC_get, _nucleardata.NUCLEAR_DATA_XE2_MAC_set)
    __swig_setmethods__["K_INF_NO_XE"] = _nucleardata.NUCLEAR_DATA_K_INF_NO_XE_set
    __swig_getmethods__["K_INF_NO_XE"] = _nucleardata.NUCLEAR_DATA_K_INF_NO_XE_get
    if _newclass:K_INF_NO_XE = _swig_property(_nucleardata.NUCLEAR_DATA_K_INF_NO_XE_get, _nucleardata.NUCLEAR_DATA_K_INF_NO_XE_set)
    __swig_setmethods__["XE2_MIC"] = _nucleardata.NUCLEAR_DATA_XE2_MIC_set
    __swig_getmethods__["XE2_MIC"] = _nucleardata.NUCLEAR_DATA_XE2_MIC_get
    if _newclass:XE2_MIC = _swig_property(_nucleardata.NUCLEAR_DATA_XE2_MIC_get, _nucleardata.NUCLEAR_DATA_XE2_MIC_set)
    __swig_setmethods__["SM2_XE"] = _nucleardata.NUCLEAR_DATA_SM2_XE_set
    __swig_getmethods__["SM2_XE"] = _nucleardata.NUCLEAR_DATA_SM2_XE_get
    if _newclass:SM2_XE = _swig_property(_nucleardata.NUCLEAR_DATA_SM2_XE_get, _nucleardata.NUCLEAR_DATA_SM2_XE_set)
    __swig_setmethods__["K_INF_XE"] = _nucleardata.NUCLEAR_DATA_K_INF_XE_set
    __swig_getmethods__["K_INF_XE"] = _nucleardata.NUCLEAR_DATA_K_INF_XE_get
    if _newclass:K_INF_XE = _swig_property(_nucleardata.NUCLEAR_DATA_K_INF_XE_get, _nucleardata.NUCLEAR_DATA_K_INF_XE_set)
    def __init__(self): 
        this = _nucleardata.new_NUCLEAR_DATA()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _nucleardata.delete_NUCLEAR_DATA
    __del__ = lambda self : None;
NUCLEAR_DATA_swigregister = _nucleardata.NUCLEAR_DATA_swigregister
NUCLEAR_DATA_swigregister(NUCLEAR_DATA)


def get_2g_parms(*args):
  return _nucleardata.get_2g_parms(*args)
get_2g_parms = _nucleardata.get_2g_parms

def get_SM2_NO_XE_0(*args):
  return _nucleardata.get_SM2_NO_XE_0(*args)
get_SM2_NO_XE_0 = _nucleardata.get_SM2_NO_XE_0

def get_SM2_NO_XE_1(*args):
  return _nucleardata.get_SM2_NO_XE_1(*args)
get_SM2_NO_XE_1 = _nucleardata.get_SM2_NO_XE_1

def get_M2_NO_XE_0(*args):
  return _nucleardata.get_M2_NO_XE_0(*args)
get_M2_NO_XE_0 = _nucleardata.get_M2_NO_XE_0

def get_M2_NO_XE_1(*args):
  return _nucleardata.get_M2_NO_XE_1(*args)
get_M2_NO_XE_1 = _nucleardata.get_M2_NO_XE_1

def get_M2_XE_0(*args):
  return _nucleardata.get_M2_XE_0(*args)
get_M2_XE_0 = _nucleardata.get_M2_XE_0

def get_M2_XE_1(*args):
  return _nucleardata.get_M2_XE_1(*args)
get_M2_XE_1 = _nucleardata.get_M2_XE_1

def get_NUFISS1_0(*args):
  return _nucleardata.get_NUFISS1_0(*args)
get_NUFISS1_0 = _nucleardata.get_NUFISS1_0

def get_NUFISS1_1(*args):
  return _nucleardata.get_NUFISS1_1(*args)
get_NUFISS1_1 = _nucleardata.get_NUFISS1_1

def get_K2_0(*args):
  return _nucleardata.get_K2_0(*args)
get_K2_0 = _nucleardata.get_K2_0

def get_K2_1(*args):
  return _nucleardata.get_K2_1(*args)
get_K2_1 = _nucleardata.get_K2_1

def get_K1_0(*args):
  return _nucleardata.get_K1_0(*args)
get_K1_0 = _nucleardata.get_K1_0

def get_K1_1(*args):
  return _nucleardata.get_K1_1(*args)
get_K1_1 = _nucleardata.get_K1_1

def get_NUFISS2_0(*args):
  return _nucleardata.get_NUFISS2_0(*args)
get_NUFISS2_0 = _nucleardata.get_NUFISS2_0

def get_NUFISS2_1(*args):
  return _nucleardata.get_NUFISS2_1(*args)
get_NUFISS2_1 = _nucleardata.get_NUFISS2_1

def get_BOR1_NO_XE_0(*args):
  return _nucleardata.get_BOR1_NO_XE_0(*args)
get_BOR1_NO_XE_0 = _nucleardata.get_BOR1_NO_XE_0

def get_BOR1_NO_XE_1(*args):
  return _nucleardata.get_BOR1_NO_XE_1(*args)
get_BOR1_NO_XE_1 = _nucleardata.get_BOR1_NO_XE_1

def get_BOR2_XE_0(*args):
  return _nucleardata.get_BOR2_XE_0(*args)
get_BOR2_XE_0 = _nucleardata.get_BOR2_XE_0

def get_BOR2_XE_1(*args):
  return _nucleardata.get_BOR2_XE_1(*args)
get_BOR2_XE_1 = _nucleardata.get_BOR2_XE_1

def get_REMOV1_0(*args):
  return _nucleardata.get_REMOV1_0(*args)
get_REMOV1_0 = _nucleardata.get_REMOV1_0

def get_REMOV1_1(*args):
  return _nucleardata.get_REMOV1_1(*args)
get_REMOV1_1 = _nucleardata.get_REMOV1_1

def get_DIFF2_0(*args):
  return _nucleardata.get_DIFF2_0(*args)
get_DIFF2_0 = _nucleardata.get_DIFF2_0

def get_DIFF2_1(*args):
  return _nucleardata.get_DIFF2_1(*args)
get_DIFF2_1 = _nucleardata.get_DIFF2_1

def get_DIFF1_0(*args):
  return _nucleardata.get_DIFF1_0(*args)
get_DIFF1_0 = _nucleardata.get_DIFF1_0

def get_DIFF1_1(*args):
  return _nucleardata.get_DIFF1_1(*args)
get_DIFF1_1 = _nucleardata.get_DIFF1_1

def get_BOR1_XE_0(*args):
  return _nucleardata.get_BOR1_XE_0(*args)
get_BOR1_XE_0 = _nucleardata.get_BOR1_XE_0

def get_BOR1_XE_1(*args):
  return _nucleardata.get_BOR1_XE_1(*args)
get_BOR1_XE_1 = _nucleardata.get_BOR1_XE_1

def get_XE_YIELD_0(*args):
  return _nucleardata.get_XE_YIELD_0(*args)
get_XE_YIELD_0 = _nucleardata.get_XE_YIELD_0

def get_XE_YIELD_1(*args):
  return _nucleardata.get_XE_YIELD_1(*args)
get_XE_YIELD_1 = _nucleardata.get_XE_YIELD_1

def get_NU_0(*args):
  return _nucleardata.get_NU_0(*args)
get_NU_0 = _nucleardata.get_NU_0

def get_NU_1(*args):
  return _nucleardata.get_NU_1(*args)
get_NU_1 = _nucleardata.get_NU_1

def get_BOR2_NO_XE_0(*args):
  return _nucleardata.get_BOR2_NO_XE_0(*args)
get_BOR2_NO_XE_0 = _nucleardata.get_BOR2_NO_XE_0

def get_BOR2_NO_XE_1(*args):
  return _nucleardata.get_BOR2_NO_XE_1(*args)
get_BOR2_NO_XE_1 = _nucleardata.get_BOR2_NO_XE_1

def get_KAPPA_0(*args):
  return _nucleardata.get_KAPPA_0(*args)
get_KAPPA_0 = _nucleardata.get_KAPPA_0

def get_KAPPA_1(*args):
  return _nucleardata.get_KAPPA_1(*args)
get_KAPPA_1 = _nucleardata.get_KAPPA_1

def get_ABS1_0(*args):
  return _nucleardata.get_ABS1_0(*args)
get_ABS1_0 = _nucleardata.get_ABS1_0

def get_ABS1_1(*args):
  return _nucleardata.get_ABS1_1(*args)
get_ABS1_1 = _nucleardata.get_ABS1_1

def get_ABS2_0(*args):
  return _nucleardata.get_ABS2_0(*args)
get_ABS2_0 = _nucleardata.get_ABS2_0

def get_ABS2_1(*args):
  return _nucleardata.get_ABS2_1(*args)
get_ABS2_1 = _nucleardata.get_ABS2_1

def get_XE2_MAC_0(*args):
  return _nucleardata.get_XE2_MAC_0(*args)
get_XE2_MAC_0 = _nucleardata.get_XE2_MAC_0

def get_XE2_MAC_1(*args):
  return _nucleardata.get_XE2_MAC_1(*args)
get_XE2_MAC_1 = _nucleardata.get_XE2_MAC_1

def get_K_INF_NO_XE_0(*args):
  return _nucleardata.get_K_INF_NO_XE_0(*args)
get_K_INF_NO_XE_0 = _nucleardata.get_K_INF_NO_XE_0

def get_K_INF_NO_XE_1(*args):
  return _nucleardata.get_K_INF_NO_XE_1(*args)
get_K_INF_NO_XE_1 = _nucleardata.get_K_INF_NO_XE_1

def get_XE2_MIC_0(*args):
  return _nucleardata.get_XE2_MIC_0(*args)
get_XE2_MIC_0 = _nucleardata.get_XE2_MIC_0

def get_XE2_MIC_1(*args):
  return _nucleardata.get_XE2_MIC_1(*args)
get_XE2_MIC_1 = _nucleardata.get_XE2_MIC_1

def get_SM2_XE_0(*args):
  return _nucleardata.get_SM2_XE_0(*args)
get_SM2_XE_0 = _nucleardata.get_SM2_XE_0

def get_SM2_XE_1(*args):
  return _nucleardata.get_SM2_XE_1(*args)
get_SM2_XE_1 = _nucleardata.get_SM2_XE_1

def get_K_INF_XE_0(*args):
  return _nucleardata.get_K_INF_XE_0(*args)
get_K_INF_XE_0 = _nucleardata.get_K_INF_XE_0

def get_K_INF_XE_1(*args):
  return _nucleardata.get_K_INF_XE_1(*args)
get_K_INF_XE_1 = _nucleardata.get_K_INF_XE_1

def get_SM2_NO_XE_IFBA_DIFF_0(*args):
  return _nucleardata.get_SM2_NO_XE_IFBA_DIFF_0(*args)
get_SM2_NO_XE_IFBA_DIFF_0 = _nucleardata.get_SM2_NO_XE_IFBA_DIFF_0

def get_SM2_NO_XE_IFBA_DIFF_1(*args):
  return _nucleardata.get_SM2_NO_XE_IFBA_DIFF_1(*args)
get_SM2_NO_XE_IFBA_DIFF_1 = _nucleardata.get_SM2_NO_XE_IFBA_DIFF_1

def get_SM2_NO_XE_IFBA_DIFF_2(*args):
  return _nucleardata.get_SM2_NO_XE_IFBA_DIFF_2(*args)
get_SM2_NO_XE_IFBA_DIFF_2 = _nucleardata.get_SM2_NO_XE_IFBA_DIFF_2

def get_M2_NO_XE_IFBA_DIFF_0(*args):
  return _nucleardata.get_M2_NO_XE_IFBA_DIFF_0(*args)
get_M2_NO_XE_IFBA_DIFF_0 = _nucleardata.get_M2_NO_XE_IFBA_DIFF_0

def get_M2_NO_XE_IFBA_DIFF_1(*args):
  return _nucleardata.get_M2_NO_XE_IFBA_DIFF_1(*args)
get_M2_NO_XE_IFBA_DIFF_1 = _nucleardata.get_M2_NO_XE_IFBA_DIFF_1

def get_M2_NO_XE_IFBA_DIFF_2(*args):
  return _nucleardata.get_M2_NO_XE_IFBA_DIFF_2(*args)
get_M2_NO_XE_IFBA_DIFF_2 = _nucleardata.get_M2_NO_XE_IFBA_DIFF_2

def get_M2_XE_IFBA_DIFF_0(*args):
  return _nucleardata.get_M2_XE_IFBA_DIFF_0(*args)
get_M2_XE_IFBA_DIFF_0 = _nucleardata.get_M2_XE_IFBA_DIFF_0

def get_M2_XE_IFBA_DIFF_1(*args):
  return _nucleardata.get_M2_XE_IFBA_DIFF_1(*args)
get_M2_XE_IFBA_DIFF_1 = _nucleardata.get_M2_XE_IFBA_DIFF_1

def get_M2_XE_IFBA_DIFF_2(*args):
  return _nucleardata.get_M2_XE_IFBA_DIFF_2(*args)
get_M2_XE_IFBA_DIFF_2 = _nucleardata.get_M2_XE_IFBA_DIFF_2

def get_NUFISS1_IFBA_DIFF_0(*args):
  return _nucleardata.get_NUFISS1_IFBA_DIFF_0(*args)
get_NUFISS1_IFBA_DIFF_0 = _nucleardata.get_NUFISS1_IFBA_DIFF_0

def get_NUFISS1_IFBA_DIFF_1(*args):
  return _nucleardata.get_NUFISS1_IFBA_DIFF_1(*args)
get_NUFISS1_IFBA_DIFF_1 = _nucleardata.get_NUFISS1_IFBA_DIFF_1

def get_NUFISS1_IFBA_DIFF_2(*args):
  return _nucleardata.get_NUFISS1_IFBA_DIFF_2(*args)
get_NUFISS1_IFBA_DIFF_2 = _nucleardata.get_NUFISS1_IFBA_DIFF_2

def get_K2_IFBA_DIFF_0(*args):
  return _nucleardata.get_K2_IFBA_DIFF_0(*args)
get_K2_IFBA_DIFF_0 = _nucleardata.get_K2_IFBA_DIFF_0

def get_K2_IFBA_DIFF_1(*args):
  return _nucleardata.get_K2_IFBA_DIFF_1(*args)
get_K2_IFBA_DIFF_1 = _nucleardata.get_K2_IFBA_DIFF_1

def get_K2_IFBA_DIFF_2(*args):
  return _nucleardata.get_K2_IFBA_DIFF_2(*args)
get_K2_IFBA_DIFF_2 = _nucleardata.get_K2_IFBA_DIFF_2

def get_K1_IFBA_DIFF_0(*args):
  return _nucleardata.get_K1_IFBA_DIFF_0(*args)
get_K1_IFBA_DIFF_0 = _nucleardata.get_K1_IFBA_DIFF_0

def get_K1_IFBA_DIFF_1(*args):
  return _nucleardata.get_K1_IFBA_DIFF_1(*args)
get_K1_IFBA_DIFF_1 = _nucleardata.get_K1_IFBA_DIFF_1

def get_K1_IFBA_DIFF_2(*args):
  return _nucleardata.get_K1_IFBA_DIFF_2(*args)
get_K1_IFBA_DIFF_2 = _nucleardata.get_K1_IFBA_DIFF_2

def get_NUFISS2_IFBA_DIFF_0(*args):
  return _nucleardata.get_NUFISS2_IFBA_DIFF_0(*args)
get_NUFISS2_IFBA_DIFF_0 = _nucleardata.get_NUFISS2_IFBA_DIFF_0

def get_NUFISS2_IFBA_DIFF_1(*args):
  return _nucleardata.get_NUFISS2_IFBA_DIFF_1(*args)
get_NUFISS2_IFBA_DIFF_1 = _nucleardata.get_NUFISS2_IFBA_DIFF_1

def get_NUFISS2_IFBA_DIFF_2(*args):
  return _nucleardata.get_NUFISS2_IFBA_DIFF_2(*args)
get_NUFISS2_IFBA_DIFF_2 = _nucleardata.get_NUFISS2_IFBA_DIFF_2

def get_BOR1_NO_XE_IFBA_DIFF_0(*args):
  return _nucleardata.get_BOR1_NO_XE_IFBA_DIFF_0(*args)
get_BOR1_NO_XE_IFBA_DIFF_0 = _nucleardata.get_BOR1_NO_XE_IFBA_DIFF_0

def get_BOR1_NO_XE_IFBA_DIFF_1(*args):
  return _nucleardata.get_BOR1_NO_XE_IFBA_DIFF_1(*args)
get_BOR1_NO_XE_IFBA_DIFF_1 = _nucleardata.get_BOR1_NO_XE_IFBA_DIFF_1

def get_BOR1_NO_XE_IFBA_DIFF_2(*args):
  return _nucleardata.get_BOR1_NO_XE_IFBA_DIFF_2(*args)
get_BOR1_NO_XE_IFBA_DIFF_2 = _nucleardata.get_BOR1_NO_XE_IFBA_DIFF_2

def get_BOR2_XE_IFBA_DIFF_0(*args):
  return _nucleardata.get_BOR2_XE_IFBA_DIFF_0(*args)
get_BOR2_XE_IFBA_DIFF_0 = _nucleardata.get_BOR2_XE_IFBA_DIFF_0

def get_BOR2_XE_IFBA_DIFF_1(*args):
  return _nucleardata.get_BOR2_XE_IFBA_DIFF_1(*args)
get_BOR2_XE_IFBA_DIFF_1 = _nucleardata.get_BOR2_XE_IFBA_DIFF_1

def get_BOR2_XE_IFBA_DIFF_2(*args):
  return _nucleardata.get_BOR2_XE_IFBA_DIFF_2(*args)
get_BOR2_XE_IFBA_DIFF_2 = _nucleardata.get_BOR2_XE_IFBA_DIFF_2

def get_REMOV1_IFBA_DIFF_0(*args):
  return _nucleardata.get_REMOV1_IFBA_DIFF_0(*args)
get_REMOV1_IFBA_DIFF_0 = _nucleardata.get_REMOV1_IFBA_DIFF_0

def get_REMOV1_IFBA_DIFF_1(*args):
  return _nucleardata.get_REMOV1_IFBA_DIFF_1(*args)
get_REMOV1_IFBA_DIFF_1 = _nucleardata.get_REMOV1_IFBA_DIFF_1

def get_REMOV1_IFBA_DIFF_2(*args):
  return _nucleardata.get_REMOV1_IFBA_DIFF_2(*args)
get_REMOV1_IFBA_DIFF_2 = _nucleardata.get_REMOV1_IFBA_DIFF_2

def get_DIFF2_IFBA_DIFF_0(*args):
  return _nucleardata.get_DIFF2_IFBA_DIFF_0(*args)
get_DIFF2_IFBA_DIFF_0 = _nucleardata.get_DIFF2_IFBA_DIFF_0

def get_DIFF2_IFBA_DIFF_1(*args):
  return _nucleardata.get_DIFF2_IFBA_DIFF_1(*args)
get_DIFF2_IFBA_DIFF_1 = _nucleardata.get_DIFF2_IFBA_DIFF_1

def get_DIFF2_IFBA_DIFF_2(*args):
  return _nucleardata.get_DIFF2_IFBA_DIFF_2(*args)
get_DIFF2_IFBA_DIFF_2 = _nucleardata.get_DIFF2_IFBA_DIFF_2

def get_DIFF1_IFBA_DIFF_0(*args):
  return _nucleardata.get_DIFF1_IFBA_DIFF_0(*args)
get_DIFF1_IFBA_DIFF_0 = _nucleardata.get_DIFF1_IFBA_DIFF_0

def get_DIFF1_IFBA_DIFF_1(*args):
  return _nucleardata.get_DIFF1_IFBA_DIFF_1(*args)
get_DIFF1_IFBA_DIFF_1 = _nucleardata.get_DIFF1_IFBA_DIFF_1

def get_DIFF1_IFBA_DIFF_2(*args):
  return _nucleardata.get_DIFF1_IFBA_DIFF_2(*args)
get_DIFF1_IFBA_DIFF_2 = _nucleardata.get_DIFF1_IFBA_DIFF_2

def get_BOR1_XE_IFBA_DIFF_0(*args):
  return _nucleardata.get_BOR1_XE_IFBA_DIFF_0(*args)
get_BOR1_XE_IFBA_DIFF_0 = _nucleardata.get_BOR1_XE_IFBA_DIFF_0

def get_BOR1_XE_IFBA_DIFF_1(*args):
  return _nucleardata.get_BOR1_XE_IFBA_DIFF_1(*args)
get_BOR1_XE_IFBA_DIFF_1 = _nucleardata.get_BOR1_XE_IFBA_DIFF_1

def get_BOR1_XE_IFBA_DIFF_2(*args):
  return _nucleardata.get_BOR1_XE_IFBA_DIFF_2(*args)
get_BOR1_XE_IFBA_DIFF_2 = _nucleardata.get_BOR1_XE_IFBA_DIFF_2

def get_XE_YIELD_IFBA_DIFF_0(*args):
  return _nucleardata.get_XE_YIELD_IFBA_DIFF_0(*args)
get_XE_YIELD_IFBA_DIFF_0 = _nucleardata.get_XE_YIELD_IFBA_DIFF_0

def get_XE_YIELD_IFBA_DIFF_1(*args):
  return _nucleardata.get_XE_YIELD_IFBA_DIFF_1(*args)
get_XE_YIELD_IFBA_DIFF_1 = _nucleardata.get_XE_YIELD_IFBA_DIFF_1

def get_XE_YIELD_IFBA_DIFF_2(*args):
  return _nucleardata.get_XE_YIELD_IFBA_DIFF_2(*args)
get_XE_YIELD_IFBA_DIFF_2 = _nucleardata.get_XE_YIELD_IFBA_DIFF_2

def get_NU_IFBA_DIFF_0(*args):
  return _nucleardata.get_NU_IFBA_DIFF_0(*args)
get_NU_IFBA_DIFF_0 = _nucleardata.get_NU_IFBA_DIFF_0

def get_NU_IFBA_DIFF_1(*args):
  return _nucleardata.get_NU_IFBA_DIFF_1(*args)
get_NU_IFBA_DIFF_1 = _nucleardata.get_NU_IFBA_DIFF_1

def get_NU_IFBA_DIFF_2(*args):
  return _nucleardata.get_NU_IFBA_DIFF_2(*args)
get_NU_IFBA_DIFF_2 = _nucleardata.get_NU_IFBA_DIFF_2

def get_BOR2_NO_XE_IFBA_DIFF_0(*args):
  return _nucleardata.get_BOR2_NO_XE_IFBA_DIFF_0(*args)
get_BOR2_NO_XE_IFBA_DIFF_0 = _nucleardata.get_BOR2_NO_XE_IFBA_DIFF_0

def get_BOR2_NO_XE_IFBA_DIFF_1(*args):
  return _nucleardata.get_BOR2_NO_XE_IFBA_DIFF_1(*args)
get_BOR2_NO_XE_IFBA_DIFF_1 = _nucleardata.get_BOR2_NO_XE_IFBA_DIFF_1

def get_BOR2_NO_XE_IFBA_DIFF_2(*args):
  return _nucleardata.get_BOR2_NO_XE_IFBA_DIFF_2(*args)
get_BOR2_NO_XE_IFBA_DIFF_2 = _nucleardata.get_BOR2_NO_XE_IFBA_DIFF_2

def get_KAPPA_IFBA_DIFF_0(*args):
  return _nucleardata.get_KAPPA_IFBA_DIFF_0(*args)
get_KAPPA_IFBA_DIFF_0 = _nucleardata.get_KAPPA_IFBA_DIFF_0

def get_KAPPA_IFBA_DIFF_1(*args):
  return _nucleardata.get_KAPPA_IFBA_DIFF_1(*args)
get_KAPPA_IFBA_DIFF_1 = _nucleardata.get_KAPPA_IFBA_DIFF_1

def get_KAPPA_IFBA_DIFF_2(*args):
  return _nucleardata.get_KAPPA_IFBA_DIFF_2(*args)
get_KAPPA_IFBA_DIFF_2 = _nucleardata.get_KAPPA_IFBA_DIFF_2

def get_ABS1_IFBA_DIFF_0(*args):
  return _nucleardata.get_ABS1_IFBA_DIFF_0(*args)
get_ABS1_IFBA_DIFF_0 = _nucleardata.get_ABS1_IFBA_DIFF_0

def get_ABS1_IFBA_DIFF_1(*args):
  return _nucleardata.get_ABS1_IFBA_DIFF_1(*args)
get_ABS1_IFBA_DIFF_1 = _nucleardata.get_ABS1_IFBA_DIFF_1

def get_ABS1_IFBA_DIFF_2(*args):
  return _nucleardata.get_ABS1_IFBA_DIFF_2(*args)
get_ABS1_IFBA_DIFF_2 = _nucleardata.get_ABS1_IFBA_DIFF_2

def get_ABS2_IFBA_DIFF_0(*args):
  return _nucleardata.get_ABS2_IFBA_DIFF_0(*args)
get_ABS2_IFBA_DIFF_0 = _nucleardata.get_ABS2_IFBA_DIFF_0

def get_ABS2_IFBA_DIFF_1(*args):
  return _nucleardata.get_ABS2_IFBA_DIFF_1(*args)
get_ABS2_IFBA_DIFF_1 = _nucleardata.get_ABS2_IFBA_DIFF_1

def get_ABS2_IFBA_DIFF_2(*args):
  return _nucleardata.get_ABS2_IFBA_DIFF_2(*args)
get_ABS2_IFBA_DIFF_2 = _nucleardata.get_ABS2_IFBA_DIFF_2

def get_XE2_MAC_IFBA_DIFF_0(*args):
  return _nucleardata.get_XE2_MAC_IFBA_DIFF_0(*args)
get_XE2_MAC_IFBA_DIFF_0 = _nucleardata.get_XE2_MAC_IFBA_DIFF_0

def get_XE2_MAC_IFBA_DIFF_1(*args):
  return _nucleardata.get_XE2_MAC_IFBA_DIFF_1(*args)
get_XE2_MAC_IFBA_DIFF_1 = _nucleardata.get_XE2_MAC_IFBA_DIFF_1

def get_XE2_MAC_IFBA_DIFF_2(*args):
  return _nucleardata.get_XE2_MAC_IFBA_DIFF_2(*args)
get_XE2_MAC_IFBA_DIFF_2 = _nucleardata.get_XE2_MAC_IFBA_DIFF_2

def get_K_INF_NO_XE_IFBA_DIFF_0(*args):
  return _nucleardata.get_K_INF_NO_XE_IFBA_DIFF_0(*args)
get_K_INF_NO_XE_IFBA_DIFF_0 = _nucleardata.get_K_INF_NO_XE_IFBA_DIFF_0

def get_K_INF_NO_XE_IFBA_DIFF_1(*args):
  return _nucleardata.get_K_INF_NO_XE_IFBA_DIFF_1(*args)
get_K_INF_NO_XE_IFBA_DIFF_1 = _nucleardata.get_K_INF_NO_XE_IFBA_DIFF_1

def get_K_INF_NO_XE_IFBA_DIFF_2(*args):
  return _nucleardata.get_K_INF_NO_XE_IFBA_DIFF_2(*args)
get_K_INF_NO_XE_IFBA_DIFF_2 = _nucleardata.get_K_INF_NO_XE_IFBA_DIFF_2

def get_XE2_MIC_IFBA_DIFF_0(*args):
  return _nucleardata.get_XE2_MIC_IFBA_DIFF_0(*args)
get_XE2_MIC_IFBA_DIFF_0 = _nucleardata.get_XE2_MIC_IFBA_DIFF_0

def get_XE2_MIC_IFBA_DIFF_1(*args):
  return _nucleardata.get_XE2_MIC_IFBA_DIFF_1(*args)
get_XE2_MIC_IFBA_DIFF_1 = _nucleardata.get_XE2_MIC_IFBA_DIFF_1

def get_XE2_MIC_IFBA_DIFF_2(*args):
  return _nucleardata.get_XE2_MIC_IFBA_DIFF_2(*args)
get_XE2_MIC_IFBA_DIFF_2 = _nucleardata.get_XE2_MIC_IFBA_DIFF_2

def get_SM2_XE_IFBA_DIFF_0(*args):
  return _nucleardata.get_SM2_XE_IFBA_DIFF_0(*args)
get_SM2_XE_IFBA_DIFF_0 = _nucleardata.get_SM2_XE_IFBA_DIFF_0

def get_SM2_XE_IFBA_DIFF_1(*args):
  return _nucleardata.get_SM2_XE_IFBA_DIFF_1(*args)
get_SM2_XE_IFBA_DIFF_1 = _nucleardata.get_SM2_XE_IFBA_DIFF_1

def get_SM2_XE_IFBA_DIFF_2(*args):
  return _nucleardata.get_SM2_XE_IFBA_DIFF_2(*args)
get_SM2_XE_IFBA_DIFF_2 = _nucleardata.get_SM2_XE_IFBA_DIFF_2

def get_K_INF_XE_IFBA_DIFF_0(*args):
  return _nucleardata.get_K_INF_XE_IFBA_DIFF_0(*args)
get_K_INF_XE_IFBA_DIFF_0 = _nucleardata.get_K_INF_XE_IFBA_DIFF_0

def get_K_INF_XE_IFBA_DIFF_1(*args):
  return _nucleardata.get_K_INF_XE_IFBA_DIFF_1(*args)
get_K_INF_XE_IFBA_DIFF_1 = _nucleardata.get_K_INF_XE_IFBA_DIFF_1

def get_K_INF_XE_IFBA_DIFF_2(*args):
  return _nucleardata.get_K_INF_XE_IFBA_DIFF_2(*args)
get_K_INF_XE_IFBA_DIFF_2 = _nucleardata.get_K_INF_XE_IFBA_DIFF_2

def get_SM2_NO_XE_WABA_DIFF_0(*args):
  return _nucleardata.get_SM2_NO_XE_WABA_DIFF_0(*args)
get_SM2_NO_XE_WABA_DIFF_0 = _nucleardata.get_SM2_NO_XE_WABA_DIFF_0

def get_SM2_NO_XE_WABA_DIFF_1(*args):
  return _nucleardata.get_SM2_NO_XE_WABA_DIFF_1(*args)
get_SM2_NO_XE_WABA_DIFF_1 = _nucleardata.get_SM2_NO_XE_WABA_DIFF_1

def get_SM2_NO_XE_WABA_DIFF_2(*args):
  return _nucleardata.get_SM2_NO_XE_WABA_DIFF_2(*args)
get_SM2_NO_XE_WABA_DIFF_2 = _nucleardata.get_SM2_NO_XE_WABA_DIFF_2

def get_M2_NO_XE_WABA_DIFF_0(*args):
  return _nucleardata.get_M2_NO_XE_WABA_DIFF_0(*args)
get_M2_NO_XE_WABA_DIFF_0 = _nucleardata.get_M2_NO_XE_WABA_DIFF_0

def get_M2_NO_XE_WABA_DIFF_1(*args):
  return _nucleardata.get_M2_NO_XE_WABA_DIFF_1(*args)
get_M2_NO_XE_WABA_DIFF_1 = _nucleardata.get_M2_NO_XE_WABA_DIFF_1

def get_M2_NO_XE_WABA_DIFF_2(*args):
  return _nucleardata.get_M2_NO_XE_WABA_DIFF_2(*args)
get_M2_NO_XE_WABA_DIFF_2 = _nucleardata.get_M2_NO_XE_WABA_DIFF_2

def get_M2_XE_WABA_DIFF_0(*args):
  return _nucleardata.get_M2_XE_WABA_DIFF_0(*args)
get_M2_XE_WABA_DIFF_0 = _nucleardata.get_M2_XE_WABA_DIFF_0

def get_M2_XE_WABA_DIFF_1(*args):
  return _nucleardata.get_M2_XE_WABA_DIFF_1(*args)
get_M2_XE_WABA_DIFF_1 = _nucleardata.get_M2_XE_WABA_DIFF_1

def get_M2_XE_WABA_DIFF_2(*args):
  return _nucleardata.get_M2_XE_WABA_DIFF_2(*args)
get_M2_XE_WABA_DIFF_2 = _nucleardata.get_M2_XE_WABA_DIFF_2

def get_NUFISS1_WABA_DIFF_0(*args):
  return _nucleardata.get_NUFISS1_WABA_DIFF_0(*args)
get_NUFISS1_WABA_DIFF_0 = _nucleardata.get_NUFISS1_WABA_DIFF_0

def get_NUFISS1_WABA_DIFF_1(*args):
  return _nucleardata.get_NUFISS1_WABA_DIFF_1(*args)
get_NUFISS1_WABA_DIFF_1 = _nucleardata.get_NUFISS1_WABA_DIFF_1

def get_NUFISS1_WABA_DIFF_2(*args):
  return _nucleardata.get_NUFISS1_WABA_DIFF_2(*args)
get_NUFISS1_WABA_DIFF_2 = _nucleardata.get_NUFISS1_WABA_DIFF_2

def get_K2_WABA_DIFF_0(*args):
  return _nucleardata.get_K2_WABA_DIFF_0(*args)
get_K2_WABA_DIFF_0 = _nucleardata.get_K2_WABA_DIFF_0

def get_K2_WABA_DIFF_1(*args):
  return _nucleardata.get_K2_WABA_DIFF_1(*args)
get_K2_WABA_DIFF_1 = _nucleardata.get_K2_WABA_DIFF_1

def get_K2_WABA_DIFF_2(*args):
  return _nucleardata.get_K2_WABA_DIFF_2(*args)
get_K2_WABA_DIFF_2 = _nucleardata.get_K2_WABA_DIFF_2

def get_K1_WABA_DIFF_0(*args):
  return _nucleardata.get_K1_WABA_DIFF_0(*args)
get_K1_WABA_DIFF_0 = _nucleardata.get_K1_WABA_DIFF_0

def get_K1_WABA_DIFF_1(*args):
  return _nucleardata.get_K1_WABA_DIFF_1(*args)
get_K1_WABA_DIFF_1 = _nucleardata.get_K1_WABA_DIFF_1

def get_K1_WABA_DIFF_2(*args):
  return _nucleardata.get_K1_WABA_DIFF_2(*args)
get_K1_WABA_DIFF_2 = _nucleardata.get_K1_WABA_DIFF_2

def get_NUFISS2_WABA_DIFF_0(*args):
  return _nucleardata.get_NUFISS2_WABA_DIFF_0(*args)
get_NUFISS2_WABA_DIFF_0 = _nucleardata.get_NUFISS2_WABA_DIFF_0

def get_NUFISS2_WABA_DIFF_1(*args):
  return _nucleardata.get_NUFISS2_WABA_DIFF_1(*args)
get_NUFISS2_WABA_DIFF_1 = _nucleardata.get_NUFISS2_WABA_DIFF_1

def get_NUFISS2_WABA_DIFF_2(*args):
  return _nucleardata.get_NUFISS2_WABA_DIFF_2(*args)
get_NUFISS2_WABA_DIFF_2 = _nucleardata.get_NUFISS2_WABA_DIFF_2

def get_BOR1_NO_XE_WABA_DIFF_0(*args):
  return _nucleardata.get_BOR1_NO_XE_WABA_DIFF_0(*args)
get_BOR1_NO_XE_WABA_DIFF_0 = _nucleardata.get_BOR1_NO_XE_WABA_DIFF_0

def get_BOR1_NO_XE_WABA_DIFF_1(*args):
  return _nucleardata.get_BOR1_NO_XE_WABA_DIFF_1(*args)
get_BOR1_NO_XE_WABA_DIFF_1 = _nucleardata.get_BOR1_NO_XE_WABA_DIFF_1

def get_BOR1_NO_XE_WABA_DIFF_2(*args):
  return _nucleardata.get_BOR1_NO_XE_WABA_DIFF_2(*args)
get_BOR1_NO_XE_WABA_DIFF_2 = _nucleardata.get_BOR1_NO_XE_WABA_DIFF_2

def get_BOR2_XE_WABA_DIFF_0(*args):
  return _nucleardata.get_BOR2_XE_WABA_DIFF_0(*args)
get_BOR2_XE_WABA_DIFF_0 = _nucleardata.get_BOR2_XE_WABA_DIFF_0

def get_BOR2_XE_WABA_DIFF_1(*args):
  return _nucleardata.get_BOR2_XE_WABA_DIFF_1(*args)
get_BOR2_XE_WABA_DIFF_1 = _nucleardata.get_BOR2_XE_WABA_DIFF_1

def get_BOR2_XE_WABA_DIFF_2(*args):
  return _nucleardata.get_BOR2_XE_WABA_DIFF_2(*args)
get_BOR2_XE_WABA_DIFF_2 = _nucleardata.get_BOR2_XE_WABA_DIFF_2

def get_REMOV1_WABA_DIFF_0(*args):
  return _nucleardata.get_REMOV1_WABA_DIFF_0(*args)
get_REMOV1_WABA_DIFF_0 = _nucleardata.get_REMOV1_WABA_DIFF_0

def get_REMOV1_WABA_DIFF_1(*args):
  return _nucleardata.get_REMOV1_WABA_DIFF_1(*args)
get_REMOV1_WABA_DIFF_1 = _nucleardata.get_REMOV1_WABA_DIFF_1

def get_REMOV1_WABA_DIFF_2(*args):
  return _nucleardata.get_REMOV1_WABA_DIFF_2(*args)
get_REMOV1_WABA_DIFF_2 = _nucleardata.get_REMOV1_WABA_DIFF_2

def get_DIFF2_WABA_DIFF_0(*args):
  return _nucleardata.get_DIFF2_WABA_DIFF_0(*args)
get_DIFF2_WABA_DIFF_0 = _nucleardata.get_DIFF2_WABA_DIFF_0

def get_DIFF2_WABA_DIFF_1(*args):
  return _nucleardata.get_DIFF2_WABA_DIFF_1(*args)
get_DIFF2_WABA_DIFF_1 = _nucleardata.get_DIFF2_WABA_DIFF_1

def get_DIFF2_WABA_DIFF_2(*args):
  return _nucleardata.get_DIFF2_WABA_DIFF_2(*args)
get_DIFF2_WABA_DIFF_2 = _nucleardata.get_DIFF2_WABA_DIFF_2

def get_DIFF1_WABA_DIFF_0(*args):
  return _nucleardata.get_DIFF1_WABA_DIFF_0(*args)
get_DIFF1_WABA_DIFF_0 = _nucleardata.get_DIFF1_WABA_DIFF_0

def get_DIFF1_WABA_DIFF_1(*args):
  return _nucleardata.get_DIFF1_WABA_DIFF_1(*args)
get_DIFF1_WABA_DIFF_1 = _nucleardata.get_DIFF1_WABA_DIFF_1

def get_DIFF1_WABA_DIFF_2(*args):
  return _nucleardata.get_DIFF1_WABA_DIFF_2(*args)
get_DIFF1_WABA_DIFF_2 = _nucleardata.get_DIFF1_WABA_DIFF_2

def get_BOR1_XE_WABA_DIFF_0(*args):
  return _nucleardata.get_BOR1_XE_WABA_DIFF_0(*args)
get_BOR1_XE_WABA_DIFF_0 = _nucleardata.get_BOR1_XE_WABA_DIFF_0

def get_BOR1_XE_WABA_DIFF_1(*args):
  return _nucleardata.get_BOR1_XE_WABA_DIFF_1(*args)
get_BOR1_XE_WABA_DIFF_1 = _nucleardata.get_BOR1_XE_WABA_DIFF_1

def get_BOR1_XE_WABA_DIFF_2(*args):
  return _nucleardata.get_BOR1_XE_WABA_DIFF_2(*args)
get_BOR1_XE_WABA_DIFF_2 = _nucleardata.get_BOR1_XE_WABA_DIFF_2

def get_XE_YIELD_WABA_DIFF_0(*args):
  return _nucleardata.get_XE_YIELD_WABA_DIFF_0(*args)
get_XE_YIELD_WABA_DIFF_0 = _nucleardata.get_XE_YIELD_WABA_DIFF_0

def get_XE_YIELD_WABA_DIFF_1(*args):
  return _nucleardata.get_XE_YIELD_WABA_DIFF_1(*args)
get_XE_YIELD_WABA_DIFF_1 = _nucleardata.get_XE_YIELD_WABA_DIFF_1

def get_XE_YIELD_WABA_DIFF_2(*args):
  return _nucleardata.get_XE_YIELD_WABA_DIFF_2(*args)
get_XE_YIELD_WABA_DIFF_2 = _nucleardata.get_XE_YIELD_WABA_DIFF_2

def get_NU_WABA_DIFF_0(*args):
  return _nucleardata.get_NU_WABA_DIFF_0(*args)
get_NU_WABA_DIFF_0 = _nucleardata.get_NU_WABA_DIFF_0

def get_NU_WABA_DIFF_1(*args):
  return _nucleardata.get_NU_WABA_DIFF_1(*args)
get_NU_WABA_DIFF_1 = _nucleardata.get_NU_WABA_DIFF_1

def get_NU_WABA_DIFF_2(*args):
  return _nucleardata.get_NU_WABA_DIFF_2(*args)
get_NU_WABA_DIFF_2 = _nucleardata.get_NU_WABA_DIFF_2

def get_BOR2_NO_XE_WABA_DIFF_0(*args):
  return _nucleardata.get_BOR2_NO_XE_WABA_DIFF_0(*args)
get_BOR2_NO_XE_WABA_DIFF_0 = _nucleardata.get_BOR2_NO_XE_WABA_DIFF_0

def get_BOR2_NO_XE_WABA_DIFF_1(*args):
  return _nucleardata.get_BOR2_NO_XE_WABA_DIFF_1(*args)
get_BOR2_NO_XE_WABA_DIFF_1 = _nucleardata.get_BOR2_NO_XE_WABA_DIFF_1

def get_BOR2_NO_XE_WABA_DIFF_2(*args):
  return _nucleardata.get_BOR2_NO_XE_WABA_DIFF_2(*args)
get_BOR2_NO_XE_WABA_DIFF_2 = _nucleardata.get_BOR2_NO_XE_WABA_DIFF_2

def get_KAPPA_WABA_DIFF_0(*args):
  return _nucleardata.get_KAPPA_WABA_DIFF_0(*args)
get_KAPPA_WABA_DIFF_0 = _nucleardata.get_KAPPA_WABA_DIFF_0

def get_KAPPA_WABA_DIFF_1(*args):
  return _nucleardata.get_KAPPA_WABA_DIFF_1(*args)
get_KAPPA_WABA_DIFF_1 = _nucleardata.get_KAPPA_WABA_DIFF_1

def get_KAPPA_WABA_DIFF_2(*args):
  return _nucleardata.get_KAPPA_WABA_DIFF_2(*args)
get_KAPPA_WABA_DIFF_2 = _nucleardata.get_KAPPA_WABA_DIFF_2

def get_ABS1_WABA_DIFF_0(*args):
  return _nucleardata.get_ABS1_WABA_DIFF_0(*args)
get_ABS1_WABA_DIFF_0 = _nucleardata.get_ABS1_WABA_DIFF_0

def get_ABS1_WABA_DIFF_1(*args):
  return _nucleardata.get_ABS1_WABA_DIFF_1(*args)
get_ABS1_WABA_DIFF_1 = _nucleardata.get_ABS1_WABA_DIFF_1

def get_ABS1_WABA_DIFF_2(*args):
  return _nucleardata.get_ABS1_WABA_DIFF_2(*args)
get_ABS1_WABA_DIFF_2 = _nucleardata.get_ABS1_WABA_DIFF_2

def get_ABS2_WABA_DIFF_0(*args):
  return _nucleardata.get_ABS2_WABA_DIFF_0(*args)
get_ABS2_WABA_DIFF_0 = _nucleardata.get_ABS2_WABA_DIFF_0

def get_ABS2_WABA_DIFF_1(*args):
  return _nucleardata.get_ABS2_WABA_DIFF_1(*args)
get_ABS2_WABA_DIFF_1 = _nucleardata.get_ABS2_WABA_DIFF_1

def get_ABS2_WABA_DIFF_2(*args):
  return _nucleardata.get_ABS2_WABA_DIFF_2(*args)
get_ABS2_WABA_DIFF_2 = _nucleardata.get_ABS2_WABA_DIFF_2

def get_XE2_MAC_WABA_DIFF_0(*args):
  return _nucleardata.get_XE2_MAC_WABA_DIFF_0(*args)
get_XE2_MAC_WABA_DIFF_0 = _nucleardata.get_XE2_MAC_WABA_DIFF_0

def get_XE2_MAC_WABA_DIFF_1(*args):
  return _nucleardata.get_XE2_MAC_WABA_DIFF_1(*args)
get_XE2_MAC_WABA_DIFF_1 = _nucleardata.get_XE2_MAC_WABA_DIFF_1

def get_XE2_MAC_WABA_DIFF_2(*args):
  return _nucleardata.get_XE2_MAC_WABA_DIFF_2(*args)
get_XE2_MAC_WABA_DIFF_2 = _nucleardata.get_XE2_MAC_WABA_DIFF_2

def get_K_INF_NO_XE_WABA_DIFF_0(*args):
  return _nucleardata.get_K_INF_NO_XE_WABA_DIFF_0(*args)
get_K_INF_NO_XE_WABA_DIFF_0 = _nucleardata.get_K_INF_NO_XE_WABA_DIFF_0

def get_K_INF_NO_XE_WABA_DIFF_1(*args):
  return _nucleardata.get_K_INF_NO_XE_WABA_DIFF_1(*args)
get_K_INF_NO_XE_WABA_DIFF_1 = _nucleardata.get_K_INF_NO_XE_WABA_DIFF_1

def get_K_INF_NO_XE_WABA_DIFF_2(*args):
  return _nucleardata.get_K_INF_NO_XE_WABA_DIFF_2(*args)
get_K_INF_NO_XE_WABA_DIFF_2 = _nucleardata.get_K_INF_NO_XE_WABA_DIFF_2

def get_XE2_MIC_WABA_DIFF_0(*args):
  return _nucleardata.get_XE2_MIC_WABA_DIFF_0(*args)
get_XE2_MIC_WABA_DIFF_0 = _nucleardata.get_XE2_MIC_WABA_DIFF_0

def get_XE2_MIC_WABA_DIFF_1(*args):
  return _nucleardata.get_XE2_MIC_WABA_DIFF_1(*args)
get_XE2_MIC_WABA_DIFF_1 = _nucleardata.get_XE2_MIC_WABA_DIFF_1

def get_XE2_MIC_WABA_DIFF_2(*args):
  return _nucleardata.get_XE2_MIC_WABA_DIFF_2(*args)
get_XE2_MIC_WABA_DIFF_2 = _nucleardata.get_XE2_MIC_WABA_DIFF_2

def get_SM2_XE_WABA_DIFF_0(*args):
  return _nucleardata.get_SM2_XE_WABA_DIFF_0(*args)
get_SM2_XE_WABA_DIFF_0 = _nucleardata.get_SM2_XE_WABA_DIFF_0

def get_SM2_XE_WABA_DIFF_1(*args):
  return _nucleardata.get_SM2_XE_WABA_DIFF_1(*args)
get_SM2_XE_WABA_DIFF_1 = _nucleardata.get_SM2_XE_WABA_DIFF_1

def get_SM2_XE_WABA_DIFF_2(*args):
  return _nucleardata.get_SM2_XE_WABA_DIFF_2(*args)
get_SM2_XE_WABA_DIFF_2 = _nucleardata.get_SM2_XE_WABA_DIFF_2

def get_K_INF_XE_WABA_DIFF_0(*args):
  return _nucleardata.get_K_INF_XE_WABA_DIFF_0(*args)
get_K_INF_XE_WABA_DIFF_0 = _nucleardata.get_K_INF_XE_WABA_DIFF_0

def get_K_INF_XE_WABA_DIFF_1(*args):
  return _nucleardata.get_K_INF_XE_WABA_DIFF_1(*args)
get_K_INF_XE_WABA_DIFF_1 = _nucleardata.get_K_INF_XE_WABA_DIFF_1

def get_K_INF_XE_WABA_DIFF_2(*args):
  return _nucleardata.get_K_INF_XE_WABA_DIFF_2(*args)
get_K_INF_XE_WABA_DIFF_2 = _nucleardata.get_K_INF_XE_WABA_DIFF_2

def get_SM2_NO_XE_GAD_DIFF_0(*args):
  return _nucleardata.get_SM2_NO_XE_GAD_DIFF_0(*args)
get_SM2_NO_XE_GAD_DIFF_0 = _nucleardata.get_SM2_NO_XE_GAD_DIFF_0

def get_SM2_NO_XE_GAD_DIFF_1(*args):
  return _nucleardata.get_SM2_NO_XE_GAD_DIFF_1(*args)
get_SM2_NO_XE_GAD_DIFF_1 = _nucleardata.get_SM2_NO_XE_GAD_DIFF_1

def get_SM2_NO_XE_GAD_DIFF_2(*args):
  return _nucleardata.get_SM2_NO_XE_GAD_DIFF_2(*args)
get_SM2_NO_XE_GAD_DIFF_2 = _nucleardata.get_SM2_NO_XE_GAD_DIFF_2

def get_M2_NO_XE_GAD_DIFF_0(*args):
  return _nucleardata.get_M2_NO_XE_GAD_DIFF_0(*args)
get_M2_NO_XE_GAD_DIFF_0 = _nucleardata.get_M2_NO_XE_GAD_DIFF_0

def get_M2_NO_XE_GAD_DIFF_1(*args):
  return _nucleardata.get_M2_NO_XE_GAD_DIFF_1(*args)
get_M2_NO_XE_GAD_DIFF_1 = _nucleardata.get_M2_NO_XE_GAD_DIFF_1

def get_M2_NO_XE_GAD_DIFF_2(*args):
  return _nucleardata.get_M2_NO_XE_GAD_DIFF_2(*args)
get_M2_NO_XE_GAD_DIFF_2 = _nucleardata.get_M2_NO_XE_GAD_DIFF_2

def get_M2_XE_GAD_DIFF_0(*args):
  return _nucleardata.get_M2_XE_GAD_DIFF_0(*args)
get_M2_XE_GAD_DIFF_0 = _nucleardata.get_M2_XE_GAD_DIFF_0

def get_M2_XE_GAD_DIFF_1(*args):
  return _nucleardata.get_M2_XE_GAD_DIFF_1(*args)
get_M2_XE_GAD_DIFF_1 = _nucleardata.get_M2_XE_GAD_DIFF_1

def get_M2_XE_GAD_DIFF_2(*args):
  return _nucleardata.get_M2_XE_GAD_DIFF_2(*args)
get_M2_XE_GAD_DIFF_2 = _nucleardata.get_M2_XE_GAD_DIFF_2

def get_NUFISS1_GAD_DIFF_0(*args):
  return _nucleardata.get_NUFISS1_GAD_DIFF_0(*args)
get_NUFISS1_GAD_DIFF_0 = _nucleardata.get_NUFISS1_GAD_DIFF_0

def get_NUFISS1_GAD_DIFF_1(*args):
  return _nucleardata.get_NUFISS1_GAD_DIFF_1(*args)
get_NUFISS1_GAD_DIFF_1 = _nucleardata.get_NUFISS1_GAD_DIFF_1

def get_NUFISS1_GAD_DIFF_2(*args):
  return _nucleardata.get_NUFISS1_GAD_DIFF_2(*args)
get_NUFISS1_GAD_DIFF_2 = _nucleardata.get_NUFISS1_GAD_DIFF_2

def get_K2_GAD_DIFF_0(*args):
  return _nucleardata.get_K2_GAD_DIFF_0(*args)
get_K2_GAD_DIFF_0 = _nucleardata.get_K2_GAD_DIFF_0

def get_K2_GAD_DIFF_1(*args):
  return _nucleardata.get_K2_GAD_DIFF_1(*args)
get_K2_GAD_DIFF_1 = _nucleardata.get_K2_GAD_DIFF_1

def get_K2_GAD_DIFF_2(*args):
  return _nucleardata.get_K2_GAD_DIFF_2(*args)
get_K2_GAD_DIFF_2 = _nucleardata.get_K2_GAD_DIFF_2

def get_K1_GAD_DIFF_0(*args):
  return _nucleardata.get_K1_GAD_DIFF_0(*args)
get_K1_GAD_DIFF_0 = _nucleardata.get_K1_GAD_DIFF_0

def get_K1_GAD_DIFF_1(*args):
  return _nucleardata.get_K1_GAD_DIFF_1(*args)
get_K1_GAD_DIFF_1 = _nucleardata.get_K1_GAD_DIFF_1

def get_K1_GAD_DIFF_2(*args):
  return _nucleardata.get_K1_GAD_DIFF_2(*args)
get_K1_GAD_DIFF_2 = _nucleardata.get_K1_GAD_DIFF_2

def get_NUFISS2_GAD_DIFF_0(*args):
  return _nucleardata.get_NUFISS2_GAD_DIFF_0(*args)
get_NUFISS2_GAD_DIFF_0 = _nucleardata.get_NUFISS2_GAD_DIFF_0

def get_NUFISS2_GAD_DIFF_1(*args):
  return _nucleardata.get_NUFISS2_GAD_DIFF_1(*args)
get_NUFISS2_GAD_DIFF_1 = _nucleardata.get_NUFISS2_GAD_DIFF_1

def get_NUFISS2_GAD_DIFF_2(*args):
  return _nucleardata.get_NUFISS2_GAD_DIFF_2(*args)
get_NUFISS2_GAD_DIFF_2 = _nucleardata.get_NUFISS2_GAD_DIFF_2

def get_BOR1_NO_XE_GAD_DIFF_0(*args):
  return _nucleardata.get_BOR1_NO_XE_GAD_DIFF_0(*args)
get_BOR1_NO_XE_GAD_DIFF_0 = _nucleardata.get_BOR1_NO_XE_GAD_DIFF_0

def get_BOR1_NO_XE_GAD_DIFF_1(*args):
  return _nucleardata.get_BOR1_NO_XE_GAD_DIFF_1(*args)
get_BOR1_NO_XE_GAD_DIFF_1 = _nucleardata.get_BOR1_NO_XE_GAD_DIFF_1

def get_BOR1_NO_XE_GAD_DIFF_2(*args):
  return _nucleardata.get_BOR1_NO_XE_GAD_DIFF_2(*args)
get_BOR1_NO_XE_GAD_DIFF_2 = _nucleardata.get_BOR1_NO_XE_GAD_DIFF_2

def get_BOR2_XE_GAD_DIFF_0(*args):
  return _nucleardata.get_BOR2_XE_GAD_DIFF_0(*args)
get_BOR2_XE_GAD_DIFF_0 = _nucleardata.get_BOR2_XE_GAD_DIFF_0

def get_BOR2_XE_GAD_DIFF_1(*args):
  return _nucleardata.get_BOR2_XE_GAD_DIFF_1(*args)
get_BOR2_XE_GAD_DIFF_1 = _nucleardata.get_BOR2_XE_GAD_DIFF_1

def get_BOR2_XE_GAD_DIFF_2(*args):
  return _nucleardata.get_BOR2_XE_GAD_DIFF_2(*args)
get_BOR2_XE_GAD_DIFF_2 = _nucleardata.get_BOR2_XE_GAD_DIFF_2

def get_REMOV1_GAD_DIFF_0(*args):
  return _nucleardata.get_REMOV1_GAD_DIFF_0(*args)
get_REMOV1_GAD_DIFF_0 = _nucleardata.get_REMOV1_GAD_DIFF_0

def get_REMOV1_GAD_DIFF_1(*args):
  return _nucleardata.get_REMOV1_GAD_DIFF_1(*args)
get_REMOV1_GAD_DIFF_1 = _nucleardata.get_REMOV1_GAD_DIFF_1

def get_REMOV1_GAD_DIFF_2(*args):
  return _nucleardata.get_REMOV1_GAD_DIFF_2(*args)
get_REMOV1_GAD_DIFF_2 = _nucleardata.get_REMOV1_GAD_DIFF_2

def get_DIFF2_GAD_DIFF_0(*args):
  return _nucleardata.get_DIFF2_GAD_DIFF_0(*args)
get_DIFF2_GAD_DIFF_0 = _nucleardata.get_DIFF2_GAD_DIFF_0

def get_DIFF2_GAD_DIFF_1(*args):
  return _nucleardata.get_DIFF2_GAD_DIFF_1(*args)
get_DIFF2_GAD_DIFF_1 = _nucleardata.get_DIFF2_GAD_DIFF_1

def get_DIFF2_GAD_DIFF_2(*args):
  return _nucleardata.get_DIFF2_GAD_DIFF_2(*args)
get_DIFF2_GAD_DIFF_2 = _nucleardata.get_DIFF2_GAD_DIFF_2

def get_DIFF1_GAD_DIFF_0(*args):
  return _nucleardata.get_DIFF1_GAD_DIFF_0(*args)
get_DIFF1_GAD_DIFF_0 = _nucleardata.get_DIFF1_GAD_DIFF_0

def get_DIFF1_GAD_DIFF_1(*args):
  return _nucleardata.get_DIFF1_GAD_DIFF_1(*args)
get_DIFF1_GAD_DIFF_1 = _nucleardata.get_DIFF1_GAD_DIFF_1

def get_DIFF1_GAD_DIFF_2(*args):
  return _nucleardata.get_DIFF1_GAD_DIFF_2(*args)
get_DIFF1_GAD_DIFF_2 = _nucleardata.get_DIFF1_GAD_DIFF_2

def get_BOR1_XE_GAD_DIFF_0(*args):
  return _nucleardata.get_BOR1_XE_GAD_DIFF_0(*args)
get_BOR1_XE_GAD_DIFF_0 = _nucleardata.get_BOR1_XE_GAD_DIFF_0

def get_BOR1_XE_GAD_DIFF_1(*args):
  return _nucleardata.get_BOR1_XE_GAD_DIFF_1(*args)
get_BOR1_XE_GAD_DIFF_1 = _nucleardata.get_BOR1_XE_GAD_DIFF_1

def get_BOR1_XE_GAD_DIFF_2(*args):
  return _nucleardata.get_BOR1_XE_GAD_DIFF_2(*args)
get_BOR1_XE_GAD_DIFF_2 = _nucleardata.get_BOR1_XE_GAD_DIFF_2

def get_XE_YIELD_GAD_DIFF_0(*args):
  return _nucleardata.get_XE_YIELD_GAD_DIFF_0(*args)
get_XE_YIELD_GAD_DIFF_0 = _nucleardata.get_XE_YIELD_GAD_DIFF_0

def get_XE_YIELD_GAD_DIFF_1(*args):
  return _nucleardata.get_XE_YIELD_GAD_DIFF_1(*args)
get_XE_YIELD_GAD_DIFF_1 = _nucleardata.get_XE_YIELD_GAD_DIFF_1

def get_XE_YIELD_GAD_DIFF_2(*args):
  return _nucleardata.get_XE_YIELD_GAD_DIFF_2(*args)
get_XE_YIELD_GAD_DIFF_2 = _nucleardata.get_XE_YIELD_GAD_DIFF_2

def get_NU_GAD_DIFF_0(*args):
  return _nucleardata.get_NU_GAD_DIFF_0(*args)
get_NU_GAD_DIFF_0 = _nucleardata.get_NU_GAD_DIFF_0

def get_NU_GAD_DIFF_1(*args):
  return _nucleardata.get_NU_GAD_DIFF_1(*args)
get_NU_GAD_DIFF_1 = _nucleardata.get_NU_GAD_DIFF_1

def get_NU_GAD_DIFF_2(*args):
  return _nucleardata.get_NU_GAD_DIFF_2(*args)
get_NU_GAD_DIFF_2 = _nucleardata.get_NU_GAD_DIFF_2

def get_BOR2_NO_XE_GAD_DIFF_0(*args):
  return _nucleardata.get_BOR2_NO_XE_GAD_DIFF_0(*args)
get_BOR2_NO_XE_GAD_DIFF_0 = _nucleardata.get_BOR2_NO_XE_GAD_DIFF_0

def get_BOR2_NO_XE_GAD_DIFF_1(*args):
  return _nucleardata.get_BOR2_NO_XE_GAD_DIFF_1(*args)
get_BOR2_NO_XE_GAD_DIFF_1 = _nucleardata.get_BOR2_NO_XE_GAD_DIFF_1

def get_BOR2_NO_XE_GAD_DIFF_2(*args):
  return _nucleardata.get_BOR2_NO_XE_GAD_DIFF_2(*args)
get_BOR2_NO_XE_GAD_DIFF_2 = _nucleardata.get_BOR2_NO_XE_GAD_DIFF_2

def get_KAPPA_GAD_DIFF_0(*args):
  return _nucleardata.get_KAPPA_GAD_DIFF_0(*args)
get_KAPPA_GAD_DIFF_0 = _nucleardata.get_KAPPA_GAD_DIFF_0

def get_KAPPA_GAD_DIFF_1(*args):
  return _nucleardata.get_KAPPA_GAD_DIFF_1(*args)
get_KAPPA_GAD_DIFF_1 = _nucleardata.get_KAPPA_GAD_DIFF_1

def get_KAPPA_GAD_DIFF_2(*args):
  return _nucleardata.get_KAPPA_GAD_DIFF_2(*args)
get_KAPPA_GAD_DIFF_2 = _nucleardata.get_KAPPA_GAD_DIFF_2

def get_ABS1_GAD_DIFF_0(*args):
  return _nucleardata.get_ABS1_GAD_DIFF_0(*args)
get_ABS1_GAD_DIFF_0 = _nucleardata.get_ABS1_GAD_DIFF_0

def get_ABS1_GAD_DIFF_1(*args):
  return _nucleardata.get_ABS1_GAD_DIFF_1(*args)
get_ABS1_GAD_DIFF_1 = _nucleardata.get_ABS1_GAD_DIFF_1

def get_ABS1_GAD_DIFF_2(*args):
  return _nucleardata.get_ABS1_GAD_DIFF_2(*args)
get_ABS1_GAD_DIFF_2 = _nucleardata.get_ABS1_GAD_DIFF_2

def get_ABS2_GAD_DIFF_0(*args):
  return _nucleardata.get_ABS2_GAD_DIFF_0(*args)
get_ABS2_GAD_DIFF_0 = _nucleardata.get_ABS2_GAD_DIFF_0

def get_ABS2_GAD_DIFF_1(*args):
  return _nucleardata.get_ABS2_GAD_DIFF_1(*args)
get_ABS2_GAD_DIFF_1 = _nucleardata.get_ABS2_GAD_DIFF_1

def get_ABS2_GAD_DIFF_2(*args):
  return _nucleardata.get_ABS2_GAD_DIFF_2(*args)
get_ABS2_GAD_DIFF_2 = _nucleardata.get_ABS2_GAD_DIFF_2

def get_XE2_MAC_GAD_DIFF_0(*args):
  return _nucleardata.get_XE2_MAC_GAD_DIFF_0(*args)
get_XE2_MAC_GAD_DIFF_0 = _nucleardata.get_XE2_MAC_GAD_DIFF_0

def get_XE2_MAC_GAD_DIFF_1(*args):
  return _nucleardata.get_XE2_MAC_GAD_DIFF_1(*args)
get_XE2_MAC_GAD_DIFF_1 = _nucleardata.get_XE2_MAC_GAD_DIFF_1

def get_XE2_MAC_GAD_DIFF_2(*args):
  return _nucleardata.get_XE2_MAC_GAD_DIFF_2(*args)
get_XE2_MAC_GAD_DIFF_2 = _nucleardata.get_XE2_MAC_GAD_DIFF_2

def get_K_INF_NO_XE_GAD_DIFF_0(*args):
  return _nucleardata.get_K_INF_NO_XE_GAD_DIFF_0(*args)
get_K_INF_NO_XE_GAD_DIFF_0 = _nucleardata.get_K_INF_NO_XE_GAD_DIFF_0

def get_K_INF_NO_XE_GAD_DIFF_1(*args):
  return _nucleardata.get_K_INF_NO_XE_GAD_DIFF_1(*args)
get_K_INF_NO_XE_GAD_DIFF_1 = _nucleardata.get_K_INF_NO_XE_GAD_DIFF_1

def get_K_INF_NO_XE_GAD_DIFF_2(*args):
  return _nucleardata.get_K_INF_NO_XE_GAD_DIFF_2(*args)
get_K_INF_NO_XE_GAD_DIFF_2 = _nucleardata.get_K_INF_NO_XE_GAD_DIFF_2

def get_XE2_MIC_GAD_DIFF_0(*args):
  return _nucleardata.get_XE2_MIC_GAD_DIFF_0(*args)
get_XE2_MIC_GAD_DIFF_0 = _nucleardata.get_XE2_MIC_GAD_DIFF_0

def get_XE2_MIC_GAD_DIFF_1(*args):
  return _nucleardata.get_XE2_MIC_GAD_DIFF_1(*args)
get_XE2_MIC_GAD_DIFF_1 = _nucleardata.get_XE2_MIC_GAD_DIFF_1

def get_XE2_MIC_GAD_DIFF_2(*args):
  return _nucleardata.get_XE2_MIC_GAD_DIFF_2(*args)
get_XE2_MIC_GAD_DIFF_2 = _nucleardata.get_XE2_MIC_GAD_DIFF_2

def get_SM2_XE_GAD_DIFF_0(*args):
  return _nucleardata.get_SM2_XE_GAD_DIFF_0(*args)
get_SM2_XE_GAD_DIFF_0 = _nucleardata.get_SM2_XE_GAD_DIFF_0

def get_SM2_XE_GAD_DIFF_1(*args):
  return _nucleardata.get_SM2_XE_GAD_DIFF_1(*args)
get_SM2_XE_GAD_DIFF_1 = _nucleardata.get_SM2_XE_GAD_DIFF_1

def get_SM2_XE_GAD_DIFF_2(*args):
  return _nucleardata.get_SM2_XE_GAD_DIFF_2(*args)
get_SM2_XE_GAD_DIFF_2 = _nucleardata.get_SM2_XE_GAD_DIFF_2

def get_K_INF_XE_GAD_DIFF_0(*args):
  return _nucleardata.get_K_INF_XE_GAD_DIFF_0(*args)
get_K_INF_XE_GAD_DIFF_0 = _nucleardata.get_K_INF_XE_GAD_DIFF_0

def get_K_INF_XE_GAD_DIFF_1(*args):
  return _nucleardata.get_K_INF_XE_GAD_DIFF_1(*args)
get_K_INF_XE_GAD_DIFF_1 = _nucleardata.get_K_INF_XE_GAD_DIFF_1

def get_K_INF_XE_GAD_DIFF_2(*args):
  return _nucleardata.get_K_INF_XE_GAD_DIFF_2(*args)
get_K_INF_XE_GAD_DIFF_2 = _nucleardata.get_K_INF_XE_GAD_DIFF_2


